apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume
spec:
  capacity:
   storage: 11Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-2
spec:
  capacity:
   storage: 9Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/data"