apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 10
      maxUnavailable: 0
  selector:
    matchLabels:
      app: stress
  replicas: 2
  template:
    metadata:
      labels:
        app: stress
    spec:
      containers:
      - name: stress
        image: jfusterm/stress
        command: ["/bin/sh"]
        args: ["-c", "stress --cpu 10"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: stress-deployment
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress-deployment
  targetCPUUtilizationPercentage: 20